listen: ":8443"
ohttp_private_key_file: "./keys/ohttp_private.key"
ai_backend:
  url: "http://localhost:11434"
tls:
  cert_file: "./certs/cert.pem"
  key_file: "./certs/key.pem"
# DHT 配置 (必需 - 用于发现 Relay 节点)
dht:
  enabled: true
  bootstrap_peers:
    - "/dnsaddr/sg1.bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
    - "/dnsaddr/sv15.bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"
    - "/dnsaddr/am6.bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
    - "/dnsaddr/ny5.bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
  listen_addrs:
    - "/ip4/0.0.0.0/tcp/4002"

  private_key_file: "./keys/exit_identity.key/identity.key"
  mode: "server"
  use_ipfs_bootstrap: false
