# TokenGo Exit 配置
# 私有 DHT 网络模式

ohttp_private_key_file: "./keys/ohttp_private.key"
ai_backend:
  url: "http://localhost:11434"

dht:
  listen_addrs:
    - "/ip4/0.0.0.0/tcp/4002"
  private_key_file: "./keys/exit_identity.key/identity.key"
  mode: "server"
  # bootstrap_peers 可选，默认使用内置列表
