listen: ":4433"
tls:
  cert_file: "./certs/cert.pem"
  key_file: "./certs/key.pem"
insecure_skip_verify: true

dht:
  enabled: true
  bootstrap_peers:
    - "/dnsaddr/sg1.bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
    - "/dnsaddr/sv15.bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN"
    - "/dnsaddr/am6.bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
    - "/dnsaddr/ny5.bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa"
  listen_addrs:
    - "/ip4/0.0.0.0/tcp/4003"
  external_addrs:
    - "/ip4/43.156.60.67/udp/4433"  # QUIC 服务地址，通过 DHT 广播供 Exit 发现

  private_key_file: "./keys/relay_identity.key/identity.key"
  mode: "server"
  use_ipfs_bootstrap: false
